version: "3.9"
services:
  db:
    container_name: "aston_bank"
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "bank"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5435:5432"
